### ISSUE TITLE
Cron Jobs do not retain ENV so BACKUP_COMMAND and EXPIRE_COMMAND don't work

### ISSUE THREAD

**Issue by drubin** [dangmai/docker-tarsnapper#4]
The documentation explictly suggests this as the recommended way to add additional configuration.

`"BACKUP_COMMAND=-o v -c /etc/tarsnapper.conf make"`
 `"EXPIRE_COMMAND=-o v -c /etc/tarsnapper.conf expire"`

While this works perfectly if you execute `tarsnapper-backup.sh` directly, this will never work via the cron job as cron by default does [not pass the ENV](https://serverfault.com/questions/698577/why-is-the-cron-env-different-from-the-users-env) to the jobs it executes. 

Which is why I assume there is a default `BACKUP_COMMAND=${BACKUP_COMMAND:-"-c /etc/tarsnapper.conf make"}` inside the `tarsnapper-backup.sh` file.

This is very confusing the lead to lots of debugging to figure out what is going on.

This also makes it impossible to use `$variables` inside `tarsnapper.conf`'s `exec_before`  and `exec_after` commands.  (which does just magically work! which is awesome)

Does it make sense to dump the ENV to a file and have each job read the ENV back? because currently, the configuration options like `BACKUP_COMMAND` are pretty useless when used from with inside cron.

**Comment by dangmai** [comment]
I think you're right - it's one of those things that I must have forgotten to test when I wrote it. Sorry about the wasted time to debug it!

I'll be looking at possible ways to resolve this in the next couple of days.

**Comment by dangmai** [comment]
I prefer to only set the necessary environmental variables for Cron to use instead of setting all the env vars into `/etc/environment`. I pushed a potential fix to the `env-var-fix` branch, could you try it out to see if it works for you?

Thank you for the bug report and PR regardless! :+1:

**Comment by drubin** [comment]
I took a look, I think this will solve the issue of the `BACKUP_COMMAND` and `EXPIRE_COMMAND` but it doesn't solve the issue of being able to use any o the ENV variables inside the exec_before and exec_after stages which is what makes this super awesome.

i.e being able to trigger a report after the backup or being able to run a command to export a database.

Right now I am using a custom entry point that saves the env variables I care about into ` /etc/environment`

**Comment by dangmai** [comment]
I do see the upside of putting all environmental variables into `/etc/environment`, however I'm against changing expectation of how a program (i.e. `cron`) works; furthermore it could lead to potential backwards incompatibility. I think using a custom entry point is the way to go here, hopefully it doesn't add too much work for you!

I'll merge the `env-var-fix` branch into `default` so that at least the commands work as expected. Also, as per #3 I'll take out the `expire` job since it seems to be redundant. Let me know if you find some issue with that.

**Comment by drubin** [comment]
@dangmai not at all I like the above suggestions. 

 I think it might be worth highlighting that cron doesn't actually store env variables and what work around you can do.

I can suggest an updated readme with some extra info in the next few days.
